### ISSUE TITLE
Ajouter http://localhost:3000/logout-callback aux URIs de redirection autorisées

### ISSUE THREAD

**Issue by Goumies** [france-connect/service-provider-example#12]
En voulant nous déconnecter d'une session en local, nous obtenons un message d'erreur.

URL où l'erreur est levée :
https://fcp.integ01.dev-franceconnect.fr/api/v1/logout?id_token_hint=xxx&state=customState11&post_logout_redirect_uri=http://localhost:3000/logout-callback

Message d'erreur :
Logout redirect uri does not match one of registered redirect uris.

Dans app.js, ligne 57, vous avez défini logout-callback :
`app.get('/logout-callback', oauthLogoutCallback);`

mais l'URI n'est pas reconnue.

**Comment by rdubigny** [comment]
Merci pour ce retour. Le problème à été corrigé.
