### ISSUE TITLE
Autoriser toutes les URIs de redirections par défaut

### ISSUE THREAD

**Issue by guillett** [france-connect/service-provider-example#13]
Cet exemple de fournisseur de service est super limité car la liste des URIs de redirections autorisées est très limitées et ne permet pas de faire des tests dans de nouvelles applications.

Que pensez-vous de fonctionner sur le mode blacklist plutôt que sur le mode whitelist ou au moins autoriser toutes les URIs en localhost ? Pour permettre à plus de monde d'intégrer la logique dans leurs applications sans trop faire de magouilles (ie. sans monter des serveurs passe plat en local sur le port 3000).

**Comment by kenjinsama** [comment]
Bonjour,

Une blacklist pourrait permettre à un attaquant d'attaquer en DOS un site non présent dans la blacklist par rebond via l'API FranceConnect. Une telle attaque pourrait également être utilisée pour faire bloquer les IPs des serveurs FranceConnect par divers hébergeurs.
Ne connaissant pas ta stack, je ne peut que te suggérer l'utilisation d'un reverse proxy type nginx pour réécrire tes URLs le temps de recevoir tes identifiants définitifs pour l'intégration.
